services:
  - type: web
    name: nexachat
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT nexachat.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "nexachat.onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GNEWS_API_KEY
        sync: false