# Generated by Django 6.0.3 on 2026-09-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('general', 'General'), ('technology', 'Technology'), ('business', 'Business'), ('sports', 'Sports'), ('science', 'Science')], default='general', max_length=20)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
