# Generated by Django 6.0.3 on 2026-09-19 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', 'User'), ('post', 'Post'), ('comment', 'Comment')], max_length=10)),
                ('reason', models.CharField(choices=[('spam', 'Spam or advertising'), ('harassment', 'Harassment or bullying'), ('hate', 'Hate speech'), ('inappropriate', 'Inappropriate content'), ('fake', 'Fake account'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('reviewed', 'Reviewed - action taken'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('target_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.postcomment')),
                ('target_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.post')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='chat_report_status_c80890_idx')],
            },
        ),
    ]
